/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hello.world

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RestController
import org.slf4j.Logger 
import org.slf4j.LoggerFactory

@SpringBootApplication
class App

fun main(args: Array<String>) {
	runApplication<App>(*args)
}

@RestController
class MessageResource {
    private val logger: Logger = LoggerFactory.getLogger(this::class.java)

    @GetMapping("/")
    fun getHelloWorld(): String {
        var envVar: String = System.getenv("SOME_ENV_VAR") ?: "default_value"
        logger.info("envVar = " + envVar)

        logger.trace("A TRACE Message")
        logger.debug("A DEBUG Message")
        logger.info("An INFO Message")
        logger.warn("A WARN Message")
        logger.error("An ERROR Message")
        return "Hello world! envVar = '" + envVar + "'"
    }

    @GetMapping("/hello")
    fun helloKotlin(): String {
        return "hello world"
    }

    @GetMapping("/test/exception")
    fun testException(): String {
        try {
            throw Exception("This is a test.")
        } catch (e: Exception) {
            logger.error("Exception caught:", e)
        }
        return "Exception caught"
    }
}